default: &default
  gllue:
    url: "http://116.62.206.67"
    aes_key: "e36258956d57846e"
    aes_iv: "0000000000000000"
    email: "eric.ling@atkins-associates.com"

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default